unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g escape-time 0
set -g mouse on

set-option -g default-terminal "xterm-256color"
set-option -sa terminal-features ',xterm-256color:RGB'
set-option -g allow-rename off
set-option -g renumber-windows on

set -g focus-events on

# Vim
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-pipe 'xclip -in -selection clipboard'
bind-key -T copy-mode-vi Escape send-keys -X cancel

# Window management
bind c new-window -c "#{pane_current_path}"
bind-key \\ split-window -h -c "#{pane_current_path}"
bind-key - split-window -c "#{pane_current_path}"
unbind '"'
unbind %

# Smart pane switching with awareness of vim splits
bind -n C-h run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-h) || tmux select-pane -L"
bind -n C-j run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-j) || tmux select-pane -D"
bind -n C-k run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-k) || tmux select-pane -U"
bind -n C-l run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-l) || tmux select-pane -R"
bind C-l send-keys 'C-l'

# TODO: Vim-like swap pane

# Resize panes
unbind Left
unbind Right
unbind Up
unbind Down
unbind L
bind -n Left run "(tmux display-message -p '#{pane_current_command}' | grep -iq lldb && tmux send-keys Left) || tmux resize-pane -L 10"
bind -n Right run "(tmux display-message -p '#{pane_current_command}' | grep -iq lldb && tmux send-keys Right) || tmux resize-pane -R 10"
bind -n Up run "(tmux display-message -p '#{pane_current_command}' | grep -iq lldb && tmux send-keys Up) || tmux resize-pane -U 5"
bind -n Down run "(tmux display-message -p '#{pane_current_command}' | grep -iq lldb && tmux send-keys Down) || tmux resize-pane -D 5"

# Style
set -g status-right "#{?window_bigger,[#{window_offset_x}#,#{window_offset_y}] ,} %H:%M %d-%b-%y"
set -g status-bg '#2B2D30'
set -g status-fg '#a9b7c6'
set-window-option -g window-status-current-style fg='#cc7832'
set -g pane-active-border-style fg='#ffffff'

# Quickly move windows
unbind <
unbind >
bind-key -r < swap-window -t -1 \; previous-window
bind-key -r > swap-window -t +1 \; next-window
